name: show-directory

on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: install tree
        run: |
          sudo apt-get update
          sudo apt-get install -y tree
      - run: tree .
